name: Qantas Loyalty - Weather Bit API Tests

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20.0.2'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          # 1. Download the latest tarball
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          # 2. Extract it
          tar -xf apache-jmeter-5.6.3.tgz

      - name: Performance Tests
        run: |
          mkdir -p results/
          chmod +x ./apache-jmeter-5.6.3/bin/jmeter
          ./apache-jmeter-5.6.3/bin/jmeter -n -t PerformanceTesting.jmx -l results/results.jtl -e -f -o results/html-report -Japi.key=${{secrets.API_KEY}}

      - name: Upload JMeter Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results/results.jtl
          retention-days: 30